event_id: 35655 # Event ID to fetch users
#CSVPath: "./Students-example.csv" # Uncomment this line if you want to use a .csv instead of API call. You can't use both

###################################################################################
#                                     Edit Text                                   #
###################################################################################
theme_objet: "MAMA 29/10/2025"
intitule: "MAMA d'octobre"
fonds_concerne: "FSE+" 

event_hour_duration: 2
event_days_duration: 1

morning_start_at_hour: 10
morning_start_at_minute: 0
morning_end_at_hour: 13
morning_end_at_minute: 0
afternoon_start_at_hour: -1
afternoon_start_at_minute: -1
afternoon_end_at_hour: -1
afternoon_end_at_minute: -1

comment: "MAMA + Remise de dipl√¥me"

teacher_first_name: "Bob"
teacher_last_name: "Le Bricoleur"

date_string: "29/10/2025"


###################################################################################
#                             Config (To be done once)                            #
###################################################################################
pdf_template_image: "./Configs/EmptyFSE.jpg" # Where to find the background PDF
output_folder: "./out" # In which folder we generate the .pdf files
pageLayout: "./Configs/PageLayout.yml" # Where to find PageLayout yml. (File generated with layout_editor.py script)
font:
  name: "DejaVu"
  path: "./Configs/DejaVuSans.ttf"
  size: 10
landscape: true

42API:
    tokenUrl: "https://api.intra.42.fr/oauth/token"
    endpoint: "https://api.intra.42.fr/v2"
    testpath: "/campus/41"
    uid: ""
    secret: ""
    scope: "public"