CSVPath: "./configs/students-example.csv" # Path to the CSV to use for the student list (see students-example.csv)

###################################################################################
#                                     Edit Text                                   #
###################################################################################
theme_objet: "EXAM 06/01/2026"
intitule: "Exam C4"
fonds_concerne: "FSE+"

event_hour_duration: 3
event_days_duration: 1

morning_start_at_hour: -1
morning_start_at_minute: -1
morning_end_at_hour: -1
morning_end_at_minute: -1
afternoon_start_at_hour: 14
afternoon_start_at_minute: 0
afternoon_end_at_hour: 17
afternoon_end_at_minute: 0

comment: "Some serious comment example"

teacher_first_name: ""
teacher_last_name: ""

date_string: "06/01/2026"


###################################################################################
#                             Config (To be done once)                            #
###################################################################################
pdf_template_image: "./page/EmptyFSE.pdf" # Where to find the background PDF
output_folder: "./out/csv" # In which folder we generate the .pdf files
pageLayout: "./page/PageLayout.yml" # Where to find PageLayout yml. (File generated with layout_editor.py script)
font:
  name: "DejaVu"
  path: "./page/DejaVuSans.ttf"
  size: 10
landscape: true

42API:
    tokenUrl: "https://api.intra.42.fr/oauth/token"
    endpoint: "https://api.intra.42.fr/v2"
    testpath: "/campus/41"
    uid: ""
    secret: ""
    scope: "public"
