theme_origin:
  x_percent: 0.12592
  y_percent: 0.210162
intitule:
  x_percent: 0.082584
  y_percent: 0.229792
fonds_concerne:
  x_percent: 0.125102
  y_percent: 0.251732
commentaire:
  x_percent: 0.69583
  y_percent: 0.254042
duree_heures:
  x_percent: 0.080131
  y_percent: 0.331409
duree_jours:
  x_percent: 0.284546
  y_percent: 0.333718
matin_h1:
  x_percent: 0.337694
  y_percent: 0.361432
matin_m1:
  x_percent: 0.426819
  y_percent: 0.362587
matin_h2:
  x_percent: 0.514309
  y_percent: 0.362587
matin_m2:
  x_percent: 0.591987
  y_percent: 0.364896
aprem_h1:
  x_percent: 0.336877
  y_percent: 0.3903
aprem_m1:
  x_percent: 0.426002
  y_percent: 0.3903
aprem_h2:
  x_percent: 0.512674
  y_percent: 0.391455
aprem_m2:
  x_percent: 0.592805
  y_percent: 0.391455
premier_nom_etudiant:
  x_percent: 0.029
  y_percent: 0.503464
nom_surveillant:
  x_percent: 0.081766
  y_percent: 0.875289
pagination:
  x_percent: 0.933769
  y_percent: 0.303695
date:
  x_percent: 0.894522
  y_percent: 0.220554
